In [5]:
from psutil import users
"""数据读取和写入   基于pandas中提供的api,可以很方便的对各类数据文件(csv,excel,数据库,网络数据等)进行读取和写入"""
import pandas as pd
#读取数据
df = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
#赋值
df['销售金额']=df['销售数量'] * df['单价']#添加一列 并为其赋值
#写入数据 --> to_csv
df.to_csv('data/sales_01.csv',index=False) #索引列不写入
df
# read_csv()：读取 csv 文件
# to_csv()：将处理后的数据写入新的 csv 文件
# index=False：写出时不保存索引列

            订单号  产品类别  产品名称  销售数量   单价  销售金额
0    6805677496  家居用品    枕头    10  199  1990
1    5857234132    食品    海苔     5   29   145
2    5888085059  电子产品  智能音箱     5  399  1995
3    6823473137    食品    面包     3   29    87
4    6801664364    食品    薯片     2   19    38
..          ...   ...   ...   ...  ...   ...
995  5887473055    图书    小说    10   49   490
996  5808511756    食品    坚果     2   79   158
997  5811169466    服装    围巾     4  129   516
998  6876456690    食品    果汁     7   39   273
999  6842608338    食品    蜂蜜     5   89   445

[1000 rows x 6 columns]

In [15]:
'''数据查看,选择及过滤'''

# 查看
print(df.head(2))   #df.head(n) 查看前n行数据
print(df.tail(2))   #df.tail(n) 查看结尾n行数据
print(df.describe())#df.describe()数值列的统计描述
print(df.info())    #df.info() 查看数据信息(列名,非空计数,数据类型)
print(df.shape)     #df.shape  属性,查看数据维度
print(df.columns)   #df.columns

          订单号  产品类别 产品名称  销售数量   单价  销售金额
0  6805677496  家居用品   枕头    10  199  1990
1  5857234132    食品   海苔     5   29   145
            订单号 产品类别 产品名称  销售数量  单价  销售金额
998  6876456690   食品   果汁     7  39   273
999  6842608338   食品   蜂蜜     5  89   445
                订单号         销售数量           单价          销售金额
count  1.000000e+03  1000.000000  1000.000000   1000.000000
mean   6.366022e+09     5.539000   388.210000   2153.611000
std    5.015131e+08     2.908769   991.380003   6275.021275
min    5.800194e+09     1.000000    19.000000     19.000000
25%    5.851898e+09     3.000000    49.000000    232.000000
50%    6.802488e+09     5.000000    89.000000    472.000000
75%    6.854162e+09     8.000000   299.000000   1196.000000
max    6.899878e+09    10.000000  5999.000000  59990.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
 5   销售金额    1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB
None
(1000, 6)
Index(['订单号', '产品类别', '产品名称', '销售数量', '单价', '销售金额'], dtype='object')

In [20]:
#数据选择
df1 = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])

#1.选择列 纵向
#1.1单列
print(df1['产品名称'].head(2))#df.列名 操作单列
#1.2多列
print(df1[['产品名称', '单价']])#操作多列

#2.选择行 -iloc,loc 横向 切片
#2.1 iloc ---》基于行号选择行(不包含结束位置) !=索引 索引可以人为指定
print(df.iloc[0:5:1] )  # df.iloc[start:stop:step] 按位置切片，不含stop
#2.2 loc  ---》基于行索引选择行(包含结束位置)  index受人为指定影响
df.loc[0:5:1]           # df.loc[start:stop:step]  按索引切片，含stop

0    枕头
1    海苔
Name: 产品名称, dtype: object
     产品名称   单价
0      枕头  199
1      海苔   29
2    智能音箱  399
3      面包   29
4      薯片   19
..    ...  ...
995    小说   49
996    坚果   79
997    围巾  129
998    果汁   39
999    蜂蜜   89

[1000 rows x 2 columns]
          订单号  产品类别  产品名称  销售数量   单价  销售金额
0  6805677496  家居用品    枕头    10  199  1990
1  5857234132    食品    海苔     5   29   145
2  5888085059  电子产品  智能音箱     5  399  1995
3  6823473137    食品    面包     3   29    87
4  6801664364    食品    薯片     2   19    38

          订单号  产品类别  产品名称  销售数量   单价  销售金额
0  6805677496  家居用品    枕头    10  199  1990
1  5857234132    食品    海苔     5   29   145
2  5888085059  电子产品  智能音箱     5  399  1995
3  6823473137    食品    面包     3   29    87
4  6801664364    食品    薯片     2   19    38
5  5897064217    图书    字帖     4   29   116

In [10]:
"""过滤---按条件筛选数据"""
# 条件筛选常用写法
# 比大小 >  <  >=  <=  ==  !=
# isin([...])：判断值是否在指定列表中
# between(a, b)：判断值是否在 a 到 b 之间
# 多条件：& 表示且，| 表示或
# 注意：多个条件时，每个条件都要加括号

# 大于等于：筛选销售数量大于等于 5 的数据
print(df[df['销售数量'] >= 5].head(2))

# isin()：筛选产品类别在“食品”和“图书”中的数据
print(df[df['产品类别'].isin(['食品', '图书'])].head(2))

# between()：筛选销售数量在 3 到 8 之间的数据
print(df[df['销售数量'].between(3, 8)].head(2))

# 且：筛选产品类别是“食品”且销售数量大于等于 3 的数据
print(df[(df['产品类别'] == '食品') & (df['销售数量'] >= 3)].head(2))

# 或：筛选产品类别是“食品”或“图书”的数据
print(df[(df['产品类别'] == '食品') | (df['产品类别'] == '图书')].head(2))

            订单号 产品类别 产品名称  销售数量   单价
997  5811169466   服装   围巾     4  129
998  6876456690   食品   果汁     7   39
999  6842608338   食品   蜂蜜     5   89
                订单号         销售数量           单价
count  1.000000e+03  1000.000000  1000.000000
mean   6.366022e+09     5.539000   388.210000
std    5.015131e+08     2.908769   991.380003
min    5.800194e+09     1.000000    19.000000
25%    5.851898e+09     3.000000    49.000000
50%    6.802488e+09     5.000000    89.000000
75%    6.854162e+09     8.000000   299.000000
max    6.899878e+09    10.000000  5999.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB
None