In [12]:
from psutil import users

"""数据读取和写入   基于pandas中提供的api,可以很方便的对各类数据文件(csv,excel,数据库,网络数据等)进行读取和写入"""
import pandas as pd
#读取数据
df = pd.read_csv('data/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
#数据处理
df['销售金额']=df['销售数量'] * df['单价']#添加一列 并为其赋值
#写入数据 --> to_csv
df.to_csv('data/sales_01.csv',index=False) #索引列不写入
df
# read_csv()：读取 csv 文件
# to_csv()：将处理后的数据写入新的 csv 文件
# index=False：写出时不保存索引列

            订单号  产品类别  产品名称  销售数量   单价  销售金额
0    6805677496  家居用品    枕头    10  199  1990
1    5857234132    食品    海苔     5   29   145
2    5888085059  电子产品  智能音箱     5  399  1995
3    6823473137    食品    面包     3   29    87
4    6801664364    食品    薯片     2   19    38
..          ...   ...   ...   ...  ...   ...
995  5887473055    图书    小说    10   49   490
996  5808511756    食品    坚果     2   79   158
997  5811169466    服装    围巾     4  129   516
998  6876456690    食品    果汁     7   39   273
999  6842608338    食品    蜂蜜     5   89   445

[1000 rows x 6 columns]

In [16]:
'''数据查看,选择及过滤'''

# 查看
df.head(5)#查看前n行数据
df.tail(5)#查看结尾n行数据
df.describe()#数值列的统计描述
df.info()#查看数据信息(列名,非空计数,数据类型)
df.shape  #属性,查看数据维度(
df.columns

# 选择列
df['产品名称']#df.列名 操作单列
df[['产品名称', '单价']]#操作多列

# 切片
df.iloc[0:5:1]   # df.iloc[start:stop:step] 按位置切片，不含stop
df.loc[0:5:1]    # df.loc[start:stop:step]  按索引切片，含stop

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
 5   销售金额    1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

          订单号  产品类别  产品名称  销售数量   单价  销售金额
0  6805677496  家居用品    枕头    10  199  1990
1  5857234132    食品    海苔     5   29   145
2  5888085059  电子产品  智能音箱     5  399  1995
3  6823473137    食品    面包     3   29    87
4  6801664364    食品    薯片     2   19    38
5  5897064217    图书    字帖     4   29   116

In [21]:
# 条件筛选常用写法
# 比大小 >  <  >=  <=  ==  !=
# isin([...])：判断值是否在指定列表中
# between(a, b)：判断值是否在 a 到 b 之间
# 多条件：& 表示且，| 表示或
# 注意：多个条件时，每个条件都要加括号

# 大于等于：筛选销售数量大于等于 5 的数据
print(df[df['销售数量'] >= 5].head(2))

# isin()：筛选产品类别在“食品”和“图书”中的数据
print(df[df['产品类别'].isin(['食品', '图书'])].head(2))

# between()：筛选销售数量在 3 到 8 之间的数据
print(df[df['销售数量'].between(3, 8)].head(2))

# 且：筛选产品类别是“食品”且销售数量大于等于 3 的数据
print(df[(df['产品类别'] == '食品') & (df['销售数量'] >= 3)].head(2))

# 或：筛选产品类别是“食品”或“图书”的数据
print(df[(df['产品类别'] == '食品') | (df['产品类别'] == '图书')].head(2))

          订单号  产品类别 产品名称  销售数量   单价  销售金额
0  6805677496  家居用品   枕头    10  199  1990
1  5857234132    食品   海苔     5   29   145
          订单号 产品类别 产品名称  销售数量  单价  销售金额
1  5857234132   食品   海苔     5  29   145
3  6823473137   食品   面包     3  29    87
          订单号  产品类别  产品名称  销售数量   单价  销售金额
1  5857234132    食品    海苔     5   29   145
2  5888085059  电子产品  智能音箱     5  399  1995
          订单号 产品类别 产品名称  销售数量  单价  销售金额
1  5857234132   食品   海苔     5  29   145
3  6823473137   食品   面包     3  29    87
          订单号 产品类别 产品名称  销售数量  单价  销售金额
1  5857234132   食品   海苔     5  29   145
3  6823473137   食品   面包     3  29    87