In [3]:
import pandas as pd

#1.读取数据
df = pd.read_csv('data/sales02.csv',nrows=10)

#2.排序
"""数据排序时,一般是升序/降序两种排列方式
升序:df.sort_values(by=['列名'],ascending=True)
降序:df.sort_values(by=['列名'],ascending=False)
Pandas支持多列排序,需分别指定ascending的值,多列排序时.第一个值一样,再排第二个
"""

#2.1 根据 销售数量 倒序排序
df.sort_values('销售数量',ascending=False)

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
9  5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04

In [5]:
#2.2 根据 单价 升序排序
df.sort_values('单价',ascending=True)
df.sort_values('单价') #Default:ascending=True

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
9  5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01

In [6]:
#2.3 根据 单价 升序排序,价格一样,再根据 销售数量 倒序排序
df.sort_values(['单价','销售数量'],ascending=[True,False])

          订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
6  6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
4  6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
1  5857234132    食品    海苔     5   29     天津    现金  2025-06-01
5  5897064217    图书    字帖     4   29     广州    现金  2025-06-02
3  6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
9  5888085059    图书    字典     2   99     青岛  微信支付  2025-06-04
0  6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
7  6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8  5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
2  5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01