In [10]:
from pandas.core.methods.to_dict import to_dict

"""数据分组:把数据按照某个特征分成不同的组,然后对每个组分别进行统计计算
常见方法:
分组后求和: df.groupby('特征')['需要统计的值').sum()
分组后统计数量: df.groupby('特征')['需要统计的值').count()
分组后求最大值: df.groupby('特征')['需要统计的值').max()
分组后求最小值: df.groupby('特征')['需要统计的值').max()
分组后求平均值: df.groupby('特征')['需要统计的值').mean()
聚合方法:df.groupby('特征')['需要统计的值').agg(['sum','count','max','min','mean'])
"""
import pandas as pd

#1.读取数据
df = pd.read_csv('data/sales02.csv',nrows=20)
df['销售金额']=df['单价']*df['销售数量']

#2.分组

#2.1 根据 产品类别 分组,统计各个类别的 订单数量 -count
df.groupby('产品类别').count()#统计时缺失值不参与统计--》选无缺失值的列

      订单号  产品名称  销售数量  单价  客户所在城市  支付方式  订单日期  销售金额
产品类别
图书      5     5     5   5       5     5     5     5
家居用品    3     3     3   3       3     3     3     3
服装      3     3     3   3       3     3     3     3
电子产品    4     4     4   4       4     4     4     4
食品      5     5     5   5       4     5     5     5

In [8]:
#2.2 根据 产品类别 分组,统计各个类别的 销售数量之和 -sum
df.groupby('产品类别')['销售数量'].sum()

产品类别
图书      25
家居用品    26
服装      23
电子产品    27
食品      21
Name: 销售数量, dtype: int64

In [12]:
#2.3 根据 产品类别 分组,统计各个类别的 销售金额 之和 -sum
df.groupby('产品类别')['销售金额'].sum()

产品类别
图书      1115
家居用品    4274
服装      4981
电子产品    6943
食品       689
Name: 销售金额, dtype: int64

In [13]:
#2.4 根据 产品类别 分组,统计各个类别的最低商品 单价 -min
df.groupby('产品类别')['单价'].min()

产品类别
图书      29
家居用品    49
服装     -29
电子产品    89
食品      19
Name: 单价, dtype: int64

In [14]:
#2.5 根据 产品类别 分组,统计各个类别的最高商品 单价 -max
df.groupby('产品类别')['单价'].max()

产品类别
图书       99
家居用品    199
服装      399
电子产品    399
食品       79
Name: 单价, dtype: int64

In [15]:
#2.6 根据 产品类别 分组,统计各个类别的平均商品 单价 -mean
df.groupby('产品类别')['单价'].mean()

产品类别
图书       51.000000
家居用品    149.000000
服装      189.666667
电子产品    246.500000
食品       37.000000
Name: 单价, dtype: float64

In [19]:
#2.7 根据 产品类别 分组,统计各个类别的商品 平均单价,最高单价,最低单价
df.groupby('产品类别')['单价'].agg(['mean','max','min'])
df.groupby('产品类别').agg  ({'单价':['mean','max','min']})

              单价
            mean  max min
产品类别
图书     51.000000   99  29
家居用品  149.000000  199  49
服装    189.666667  399 -29
电子产品  246.500000  399  89
食品     37.000000   79  19

In [20]:
#2.8 根据 产品类别 分组,统计各个类别的商品的 销售数量之和,销售金额之和,平均单价
df.groupby('产品类别').agg  ({'销售数量':'sum','销售金额':'sum','单价':'mean'})

      销售数量  销售金额          单价
产品类别
图书      25  1115   51.000000
家居用品    26  4274  149.000000
服装      23  4981  189.666667
电子产品    27  6943  246.500000
食品      21   689   37.000000

In [21]:
df.groupby('产品类别').agg  ({'销售数量':'sum','销售金额':'sum','单价':'mean'}).to_dict() #转字典

{'销售数量': {'图书': 25, '家居用品': 26, '服装': 23, '电子产品': 27, '食品': 21},
 '销售金额': {'图书': 1115, '家居用品': 4274, '服装': 4981, '电子产品': 6943, '食品': 689},
 '单价': {'图书': 51.0,
  '家居用品': 149.0,
  '服装': 189.66666666666666,
  '电子产品': 246.5,
  '食品': 37.0}}